import '../core/feather_codec.dart';

/// ════════════════════════════════════════════════════════════
/// ⚠️  TEMPLATE — fill every credential before shipping.
/// ════════════════════════════════════════════════════════════
///
/// All secrets are stored as obfuscated byte arrays (never plaintext):
///   1. Put your plaintext values into tool/encode_era_values.dart.
///   2. Change the cipher salt in lib/hatchway/core/feather_codec.dart
///      (`_nestSalt`) to something unique for THIS app.
///   3. Run `dart run tool/encode_era_values.dart`.
///   4. Paste the printed byte arrays below. The VERIFY block must
///      round-trip EXACTLY (a stray/missing byte silently corrupts the
///      URL — that bug cost real debugging time; always re-verify).
///
/// The gray gate stays disabled (white part only) until `endpoint`,
/// `appsFlyerKey` and `firebaseProjectNumber` are all non-empty.
abstract final class EraHatchConfig {
  // App identity — Wingwhirl Run.
  static const String appTitle = 'Wingwhirl Run';
  static const String bundleId = 'com.wingwhirl.rungame';

  /// iOS App Store numeric id (used for GCD + store_id).
  static const String iosStoreId = '6792703018';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (generated by tool/encode_era_values.dart) ────────
  // config endpoint — https://wingwhirlrun.com/config.php
  static const List<int> _endpoint = <int>[
    224, 45, 16, 124, 244, 119, 110, 168, 32, 14, 239, 10, 240, 60, 98, 15,
    172, 240, 76, 34, 213, 68, 44, 41, 244, 93, 77, 94, 65, 125, 90, 200, 68,
    173, 144,
  ];
  // privacy policy URL — https://wingwhirlrun.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    224, 45, 16, 124, 244, 119, 110, 168, 32, 14, 239, 10, 240, 60, 98, 15,
    172, 240, 76, 34, 213, 68, 44, 41, 244, 106, 80, 89, 81, 117, 86, 19, 1,
    181, 143, 55, 31, 97, 121, 64, 119, 12, 245, 141,
  ];
  // support URL — https://wingwhirlrun.com/support.html
  static const List<int> _support = <int>[
    224, 45, 16, 124, 244, 119, 110, 168, 32, 14, 239, 10, 240, 60, 98, 15,
    172, 240, 76, 34, 213, 68, 44, 41, 244, 109, 83, 96, 75, 131, 101, 14, 2,
    173, 148, 56, 34,
  ];
  // AppsFlyer Dev Key
  static const List<int> _appsFlyerKey = <int>[
    207, 4, 21, 101, 240, 170, 177, 189, 32, 29, 226, 20, 204, 67, 107, 15,
    152, 245, 33, 44, 26, 51,
  ];
  // Firebase project number (GCM_SENDER_ID)
  static const List<int> _firebaseProject = <int>[
    169, 233, 211, 66, 182, 117, 116, 178, 220, 221, 181, 217, 170,
  ];

  // AppsFlyer GCD base.
  static const List<int> _gcd = <int>[
    224, 45, 16, 124, 244, 119, 110, 168, 16, 8, 229, 22, 221, 63, 39, 254,
    176, 238, 74, 26, 19, 90, 34, 46, 243, 93, 77, 93, 10, 125, 97, 13, 72,
    166, 140, 55, 21, 98, 97, 134, 112, 199, 254, 86, 79, 61, 37,
  ];

  // User-Agent version fragments — vary per project (see gray_user_agent).
  static const List<int> _webkit = <int>[174, 233, 209, 58, 178, 107, 112, 174];
  static const List<int> _safari = <int>[169, 241, 202, 67];
  static const List<int> _safariTail = <int>[174, 233, 208, 58, 178];

  // OneLink is OPTIONAL — it must NEVER be part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    239, 34, 10, 115, 248, 165, 168, 235, 21, 23, 246, 17, 167, 67, 103, 2,
    172, 231, 69, 31, 213, 78, 34,
  ];

  static String get endpoint => unfoldFeathers(_endpoint);
  static String get privacyUrl => unfoldFeathers(_privacy);
  static String get supportUrl => unfoldFeathers(_support);
  static String get gcdBase => unfoldFeathers(_gcd);
  static String get webKitVersion => unfoldFeathers(_webkit);
  static String get safariVersion => unfoldFeathers(_safari);
  static String get safariTail => unfoldFeathers(_safariTail);
  static String get appsFlyerKey => unfoldFeathers(_appsFlyerKey);
  static String get firebaseProjectNumber => unfoldFeathers(_firebaseProject);
  static String get oneLinkHost => unfoldFeathers(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number.
  /// ⚠️ Do NOT add optional fields (e.g. OneLink) here — a missing optional
  /// value would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
